# Service identity
spring.application.name=auth-service
server.port=8081

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/matchmaking
spring.datasource.username=gameuser
spring.datasource.password=gamepass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (we'll use this in the next step)
jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_LATER
jwt.expiration-ms=3600000