spring.application.name=matchmaking-service
server.port=8082

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=wexK4WB7RDrSsj/t3Pibw0eqboLxryZf1ST/advE811uXSojmicQeE0Ua1kbH0YmF2Fb9mds2SMFepDp74DHtQ==